[package]
name = "smoxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy-inspector-egui = "0.21.0"
block-mesh = "0.2.0"
futures-lite = "2.1.0"
noise = "0.8.2"
